### ISSUE TITLE
pikaia with openmp?

### ISSUE THREAD

**Issue by zmiimz** [jacobwilliams/pikaia#1]
Dear Jacob,
many thanks for the updated pikaia code. 

I am just playing a bit around with it and trying to start it parallel with openmp by adding 
some cpu consuming dummy code in the Rosenbrock function  (the plan is to apply pikaia to some "real world problem") and 

a) in pikaya subroutine after "!Compute initial (random but bounded) phenotypes" comment line

``` Fortran
      !$omp parallel do private(ip)
      do ip=istart,me%np
         do k=1,me%n
            oldph(k,ip)=urand()  !from [0,1] ! urand not thread safe!
         end do
         call me%ff(oldph(:,ip),fitns(ip))
      end do
      !$omp end parallel do
```

(have also set omp_set_nested(.false.) in the example to avoid splitting k loop... )

b)  in newpop after "!replace population" comment line

``` Fortran
      !$omp parallel do private(i)
      do i=1,me%np

         oldph(:,i)=newph(:,i)

         !get fitness using caller's fitness function
         call me%ff(oldph(:,i),fitns(i))

      end do
      !$omp end parallel do
```

 It seems to bring something (not much but anyway) but I have got also 3 more questions related to the problem:
1.  Are there any other good places to do openmp  threads in the code? (mb I haven't found them?) 
2. Should Fortran built-in random generator and urand() function be parts of private objects for each openmp thread?  I.e. do we need to replace this random_number with something more portable and related to OOP ?
3. I cannot ensure reproducibility of calculation in modified version using openmp threads.  This seems to be connected with 2? Or there is some kind of limitation at the algorithm level?

**Comment by jacobwilliams** [comment]
I really like this idea!

I need to look at the code to see if I have any suggestions about where to parallelize. Definitely, the two places you show above, where the function is being evaluated over the entire population will be the most useful to parallelize.

2 and 3 are related, I think. What if we rearranged the first code block like this:

``` Fortran
      do ip=istart,me%np
         do k=1,me%n
            oldph(k,ip)=urand()  !from [0,1]
         end do
      end do

      !$omp parallel do private(ip)
      do ip=istart,me%np
         call me%ff(oldph(:,ip),fitns(ip))
      end do
      !$omp end parallel do
```

Would that make the results reproducible?

**Comment by zmiimz** [comment]
> Would that make the results reproducible?

Indeed ) But how critical is the randomization at this step for the algorithm? 

My spontaneous idea was to make something like  $omp threadprivate("random generator object")  for each thread in openmp...

**Comment by jacobwilliams** [comment]
All this code is doing is generating an initial random population and then evaluating the function for each one. So, assuming that the function is not calling the random number generator, it shouldn't matter if the `k` loop is inside or outside the loop calling the function. If the function is generating random numbers...then yes, we'd probably have to do something else.

Is the idea that we should get the exact same answer if running it with or without OpenMP? (and also for multiple runs with OpenMP)?

I'm interested to see anything you come up with. I also made an OpenMP branch that I can do some experiments on as well. I've not had any experience trying to generate random numbers in different threads before, so I don't currently know what the best solution should be.

**Comment by zmiimz** [comment]
> Is the idea that we should get the exact same answer if running it with or without OpenMP? (and also for multiple runs with OpenMP)?

Ok, you came exactly to the point.   In general, non-reproducibility is really bad.  On the other side reproducibility hurts performance a bit.  I do not expect the same answer with and without OpenMP. But I do expect that with the same starting seed and with the same number of threads (set as OMP_NUM_THREADS or with omp_set_num_threads) we should obtain in principle the same result for multiple runs.  I have to admit, that I have some experience with usual MC and deterministic algorithms only.   In MC what I usually do is to create RG for each thread (usually Mersenne Twister is good enough), init them with some random numbers ("seeds") from one input seed only (using one additional "master thread RG"),  and fix number of threads in parallel regions (by setting static schedule and disabling dynamic adjustment of threads). I see that GA might also depend  implicitly on the order of thread execution (f.e. new function results in the population), so we either need to make it deterministic or just hardcode that execution sequence order.

**Comment by ivan-pi** [comment]
Has there been any progress on the OpenMP branch? 

I am trying to use pikaia on an optimization problem with 8 variables. A single evaluation of my fitness functions takes around 10 s, meaning that with a population of 200 it is about 30 min per generation.

**Comment by ivan-pi** [comment]
I also noticed a parallel version using MPI already exists: http://www.hao.ucar.edu/Public/about/Staff/travis/mpikaia/

**Comment by poilsaunez** [comment]
I did create my own MPI version of the original Pikaia code (by Charbonneau) sometime around 2013. I was only parallelizing the call to the fitness function inside each generation, such that a 200-member population could run in parallel on up to 200 threads. Very efficient.

But, yes, reproducibility is very important, so each fitness calculation (thread) had its own independent random sequence & independent from pikaia's random gen.

**Comment by ivan-pi** [comment]
> I did create my own MPI version of the original Pikaia code (by Charbonneau) sometime around 2013. I was only parallelizing the call to the fitness function inside each generation, such that a 200-member population could run in parallel on up to 200 threads. Very efficient.

Sounds very promising. Today, I think it could be done quite elegantly using co-arrays.

**Comment by jacobwilliams** [comment]
Sorry, I haven't had a chance to revisit this. If anybody wants to contribute i'm open to it. Yes, a coarray version would be interesting.

**Comment by jacobwilliams** [comment]
I merged it into master. I think it works fine for now. probably there may be some more parallelization that could be done.
